name: stock_data_daily_refresh

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          
      - name: execute python workflows from bash script
        env: 
          DB_URL: ${{ secrets.DB_URL }}

        run: python ./stock_data_daily_refresh.py